/**
 * Parse a migration's `createdAt` stamp into a `Date`.
 *
 * Migration filenames generated by the framework carry a
 * `MM-DD-YYYY_HH-MM-SS` prefix, which **`new Date()` cannot parse** — it
 * returns `Invalid Date`. Anything ordering migrations by timestamp must come
 * through here; using the native constructor silently yields `NaN` and
 * degrades the sort into whatever its tiebreaker is.
 *
 * Supports `MM-DD-YYYY_HH-MM-SS` and `DD-MM-YYYY_HH-MM-SS`, telling them apart
 * by whether the first field exceeds 12 (a month cannot), and falls back to
 * native parsing for ISO strings.
 *
 * @returns the parsed date, or `undefined` when the stamp is unusable.
 */
export function parseCreatedAt(createdAt: string): Date | undefined {
  const match = createdAt.match(/^(\d{2})-(\d{2})-(\d{4})_(\d{2})-(\d{2})-(\d{2})$/);

  if (match) {
    const [, first, second, year, hour, minute, second_time] = match;
    const firstNum = parseInt(first);
    const secondNum = parseInt(second);

    let month: number, day: number;

    // Intelligently detect format:
    // If first > 12, it must be DD-MM-YYYY (day can't be month)
    // If second > 12, it must be MM-DD-YYYY (day can't be month)
    // Otherwise, assume MM-DD-YYYY (US format as default)
    if (firstNum > 12) {
      // DD-MM-YYYY format
      day = firstNum;
      month = secondNum;
    } else if (secondNum > 12) {
      // MM-DD-YYYY format
      month = firstNum;
      day = secondNum;
    } else {
      // Ambiguous — default to MM-DD-YYYY
      month = firstNum;
      day = secondNum;
    }

    const date = new Date(
      parseInt(year),
      month - 1, // JavaScript months are 0-indexed
      day,
      parseInt(hour),
      parseInt(minute),
      parseInt(second_time),
    );

    // Validate the date is actually valid
    if (isNaN(date.getTime())) {
      return undefined;
    }

    return date;
  }

  // Fallback to standard Date parsing for ISO strings
  try {
    const date = new Date(createdAt);

    return isNaN(date.getTime()) ? undefined : date;
  } catch {
    return undefined;
  }
}

/**
 * Compare two migration timestamps for ordering.
 *
 * Shared by every migration comparator so they cannot drift apart: a stamp
 * that parses always sorts before one that doesn't, and two unparseable
 * stamps are equal (leaving the caller's own tiebreaker to decide).
 *
 * Returns `undefined` when the timestamps do not settle the comparison.
 */
export function compareCreatedAt(
  a: string | undefined,
  b: string | undefined,
): number | undefined {
  const dateA = a ? parseCreatedAt(a) : undefined;
  const dateB = b ? parseCreatedAt(b) : undefined;

  if (dateA && dateB) {
    const difference = dateA.getTime() - dateB.getTime();

    return difference === 0 ? undefined : difference;
  }

  if (dateA) {
    return -1;
  }

  if (dateB) {
    return 1;
  }

  return undefined;
}
